### PR TITLE
SWI-3814 Fix Repeat Count Mapping Issue

### LINKED ISSUE #114: Gather repeat_count has incorrect mapping to API attribute
In the new generated SDK (11.1.0), the `Gather` verb has an incorrect mapping to the API attribute for `repeat_count`.

It should map to `repeatCount`, but it maps to `repeat_count` leading to errors in the status callback like:

```ruby
{
"cause"=>"invalid-bxml", 
"errorMessage"=>"Attribute 'repeat_count' is not allowed to appear in element 'Gather'.", 
"errorId"=>"1721e238-4d71-48d7-93b5-2becdadc07fb"
}
```

### Sample code
```ruby
> gather = Bandwidth::Bxml::Gather.new([], {max_digits: 5, repeat_count: 10})
> gather

=>
#<Bandwidth::Bxml::Gather:0x00000001326b1ce0
 @attribute_map=
  {:gather_url=>"gatherUrl",
   :gather_method=>"gatherMethod",
   :gather_fallback_url=>"gatherFallbackUrl",
   :gather_fallback_method=>"gatherFallbackMethod",
   :username=>"username",
   :password=>"password",
   :fallback_username=>"fallbackUsername",
   :fallback_password=>"fallbackPassword",
   :tag=>"tag",
   :terminating_digits=>"terminatingDigits",
   :max_digits=>"maxDigits",
   :inter_digit_timeout=>"interDigitTimeout",
   :first_digit_timeout=>"firstDigitTimeout",
   :repeat_count=>"repeat_count"},
 @attributes={:max_digits=>5, :repeat_count=>10},
 @content=nil,
 @nested_verbs=[],
 @tag="Gather">

> gather.to_bxml
=> "\n<Gather maxDigits=\"5\" repeat_count=\"10\"/>\n"
```

### Expected response
`=> "\n<Gather maxDigits=\"5\" repeatCount=\"10\"/>\n"`

### Suggested fix
Update the mapping and associated tests to use `repeatCount`

### PR DESCRIPTION
**Pull request by ckoegel**
Fixes #114

### CODE REVIEW

**Review by hamermike — APPROVED** [review]

**Review by juliajanu — DISMISSED** [review]

**Review by ajrice6713 — APPROVED** [review]

File: lib/bandwidth-sdk/models/bxml/verbs/gather.rb [hunk 1]
```diff
@@ -21,7 +21,7 @@ def initialize(audio_verbs = [], attributes = {})
...
           first_digit_timeout: 'firstDigitTimeout',       # Optional [Number]: Time (in seconds) to pause after any audio from nested <SpeakSentence> or <PlayAudio> verb is played (in seconds) before terminating the Gather. Default value is 5. Range: decimal values between 0 - 60.
-          repeat_count: 'repeat_count',                   # Optional [Number]: The number of times the audio prompt should be played if no digits are pressed. For example, if this value is 3, the nested audio clip will be played a maximum of three times. The delay between repetitions will be equal to first_digit_timeout. Default value is 1. repeat_count * number of verbs must not be greater than 20.
+          repeat_count: 'repeatCount',                    # Optional [Number]: The number of times the audio prompt should be played if no digits are pressed. For example, if this value is 3, the nested audio clip will be played a maximum of three times. The delay between repetitions will be equal to first_digit_timeout. Default value is 1. repeat_count * number of verbs must not be greater than 20.
```
Comment (juliajanu) [inline lib/bandwidth-sdk/models/bxml/verbs/gather.rb:24]: comment isn't updated
```suggestion
          repeat_count: 'repeatCount',                    # Optional [Number]: The number of times the audio prompt should be played if no digits are pressed. For example, if this value is 3, the nested audio clip will be played a maximum of three times. The delay between repetitions will be equal to first_digit_timeout. Default value is 1. repeatCount * number of verbs must not be greater than 20.
```

**Review by ajrice6713 — APPROVED** [review]

**Review by juliajanu — APPROVED** [review]
